name: Node CI
on: [push]
env:
  CI: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          clean: false
      - name: Node
        uses: actions/setup-node@v2
        with:
          node-version: "18.17.1"
          registry-url: "https://registry.npmjs.org"
      - name: Install
        run: yarn
      - name: build
        run: yarn build
      - name: test
        run: yarn test
